# Generated by Django 4.1.4 on 2022-12-13 17:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('words', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='words',
            name='time_clear',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
