# Generated by Django 4.1.4 on 2022-12-13 11:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('words', '0002_categories'),
    ]

    operations = [
        migrations.AlterField(
            model_name='users',
            name='first_name',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='users',
            name='last_name',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.CreateModel(
            name='Words',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('word', models.CharField(max_length=200, unique=True)),
                ('time_create', models.DateTimeField(auto_now_add=True)),
                ('time_clear', models.DateTimeField(blank=True)),
                ('category_id', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='words.categories')),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='words.users')),
            ],
        ),
    ]
